# Travis CI Configuration
# https://docs.travis-ci.com
## Lesser history
git:
  depth: 30

## Use container-based infrastructure for quicker build start-up
sudo: false

## We only support Ubuntu 14.04 and newer
dist: trusty

addons:
  apt:
    packages:
    - realpath # Not required least after 16.04
    - debhelper
    - autotools-dev
    - libwxgtk2.8-dev

language: cpp

compiler:
- gcc

script:
# For triggering smudge-version
- ./setup-development-environment.bash

- dpkg-buildpackage -uc -b
